mender: Fail instead of defaulting when active slot is not found
To avoid accidentally writing on top of the active slot in case of
issues with determining the active slot, fail the update instead of
defaulting.

YouTrack-Id: AXELERA-229
Change-Id: If58027ab6ee04ae7e04de4a9a2c375ba31f704a3
Signed-off-by: Patrick Barsanti <patrick.barsanti@amarulasolutions.com>

diff --git a/meta-axelera/recipes-mender/mender-voyager-update-module/files/mender-update b/meta-axelera/recipes-mender/mender-voyager-update-module/files/mender-update
--- a/meta-axelera/recipes-mender/mender-voyager-update-module/files/mender-update
+++ b/meta-axelera/recipes-mender/mender-voyager-update-module/files/mender-update
@@ -68,6 +68,13 @@ set_upgrade_vars() {
     MENDER_BOOTPART_TO_UPDATE="${MENDER_BOOT_PART_A}"
     MENDER_VBMETAPART_TO_UPDATE="${MENDER_VBMETA_PART_A}"
 
+    case "${active_num}" in
+        ''|*[!0-9]*)
+            log_message "Cannot determine the active slot: mender_boot_part='${active_num}'" 1>&2
+            return 1
+            ;;
+    esac
+
     if test "${active_num}" -eq "${MENDER_ROOTFS_PART_A_NUMBER}"; then
         active="${MENDER_ROOTFS_PART_A}"
         passive="${MENDER_ROOTFS_PART_B}"
