recipes-mender: Restore original mender.conf logic
Right now, we are forcing our own mender.conf in the target rootfs in
/etc/mender/mender.conf and creating a link to that in
/var/lib/mender/mender.conf

This causes mender to read the configs twice.
At current state, it does not cause issues.
However, since we plan to introduce signature checking in Mender, this
will cause parsing errors in the conf, e.g.:

  ERRO[0000] both ArtifactVerifyKey and ArtifactVerifyKeys are set

The original recipe for mender-client has an internal logic to intercept
mender.conf in SRC_URI, separate between persistent and transient
configs, and put them respectively in /var/lib/mender/mender.conf and
/etc/mender/mender.conf automatically.

To allow adding ArtifactVerifyKey without further hacking, leave this
logic up to the mender-client recipe.
To comply with this change, add a helper function inside our custom
parse_conf_file() function in order to merge both configs from our
mender-update script.

YouTrack-Id: AXELERA-210
Change-Id: I78b1476f231868e38882486029700338cd55c89c
Signed-off-by: Patrick Barsanti <patrick.barsanti@amarulasolutions.com>

diff --git a/meta-axelera/recipes-mender/mender-voyager-update-module/files/mender-update b/meta-axelera/recipes-mender/mender-voyager-update-module/files/mender-update
--- a/meta-axelera/recipes-mender/mender-voyager-update-module/files/mender-update
+++ b/meta-axelera/recipes-mender/mender-voyager-update-module/files/mender-update
@@ -26,25 +26,29 @@ jq_read() {
 }
 
 parse_conf_file() {
-    MENDER_BOOT_PART_A="$(jq_read '.BootPartA' /etc/mender/mender.conf)"
-    MENDER_BOOT_PART_B="$(jq_read '.BootPartB' /etc/mender/mender.conf)"
-    MENDER_ROOTFS_PART_A="$(jq_read '.RootfsPartA' /etc/mender/mender.conf)"
-    MENDER_ROOTFS_PART_B="$(jq_read '.RootfsPartB' /etc/mender/mender.conf)"
-    MENDER_VBMETA_PART_A="$(jq_read '.VbmetaPartA' /etc/mender/mender.conf)"
-    MENDER_VBMETA_PART_B="$(jq_read '.VbmetaPartB' /etc/mender/mender.conf)"
+    get_conf_val() {
+        cat /etc/mender/mender.conf /var/lib/mender/mender.conf 2>/dev/null | jq -r -s "add | .${1} // empty"
+    }
+
+    MENDER_BOOT_PART_A="$(get_conf_val BootPartA)"
+    MENDER_BOOT_PART_B="$(get_conf_val BootPartB)"
+    MENDER_ROOTFS_PART_A="$(get_conf_val RootfsPartA)"
+    MENDER_ROOTFS_PART_B="$(get_conf_val RootfsPartB)"
+    MENDER_VBMETA_PART_A="$(get_conf_val VbmetaPartA)"
+    MENDER_VBMETA_PART_B="$(get_conf_val VbmetaPartB)"
 
     if [ -z "${MENDER_BOOT_PART_A}" ] || [ -z "${MENDER_BOOT_PART_B}" ]; then
-        log_message "Cannot parse BootPartA/B in /etc/mender/mender.conf" 1>&2
+        log_message "Cannot parse BootPartA/B in either /etc/mender/mender.conf or /var/lib/mender/mender.conf" 1>&2
         return 1
     fi
 
     if [ -z "${MENDER_VBMETA_PART_A}" ] || [ -z "${MENDER_VBMETA_PART_B}" ]; then
-        log_message "Cannot parse VbmetaPartA/B in /etc/mender/mender.conf" 1>&2
+        log_message "Cannot parse VbmetaPartA/B in either /etc/mender/mender.conf or /var/lib/mender/mender.conf" 1>&2
         return 1
     fi
 
     if [ -z "${MENDER_ROOTFS_PART_A}" ] || [ -z "${MENDER_ROOTFS_PART_B}" ]; then
-        log_message "Cannot parse RootfsPartA/B in /etc/mender/mender.conf" 1>&2
+        log_message "Cannot parse RootfsPartA/B in either /etc/mender/mender.conf or /var/lib/mender/mender.conf" 1>&2
         return 1
     fi
 
