meta-axelera: Add vbmeta, misc and security partitions
To introduce secureboot support, we need to introduce some mandatory
partitions for AVB, as per Rockchip documentation.

Add vbmeta_a and vbmeta_b, which will contain some metadata for
the boot.img, like signature and hash.
Add empty misc and security partitions to satisfy bootloader
requirements.

To maintain the U-Boot env offsets equal, take a few megabytes from the
boot_a and boot_b partitions.

YouTrack-Id: AXELERA-207
Change-Id: I129ea96ae86aeb1e51eabbd54b146963ef9c5a3f
Signed-off-by: Patrick Barsanti <patrick.barsanti@amarulasolutions.com>

diff --git a/meta-axelera/recipes-mender/mender-axelera-state-scripts/files/post-install-script b/meta-axelera/recipes-mender/mender-axelera-state-scripts/files/post-install-script
--- a/meta-axelera/recipes-mender/mender-axelera-state-scripts/files/post-install-script
+++ b/meta-axelera/recipes-mender/mender-axelera-state-scripts/files/post-install-script
@@ -38,20 +38,20 @@ SOURCE_PART=""
 TARGET_BOOT_PART=""
 
 case "${MENDER_PART_NUMBER}" in
-    6)
-        # Target rootfs is p6. Source for boot.img is /dev/mmcblk0p6.
+    10)
+        # Target rootfs is p10. Source for boot.img is /dev/mmcblk0p10.
         # Target boot partition for flashing is p2.
-        SOURCE_PART="${ROOT_DEVICE}p6"
+        SOURCE_PART="${ROOT_DEVICE}p10"
         TARGET_BOOT_PART="${ROOT_DEVICE}p2"
         ;;
-    7)
-        # Target rootfs is p7. Source for boot.img is /dev/mmcblk0p7.
+    11)
+        # Target rootfs is p11. Source for boot.img is /dev/mmcblk0p11.
         # Target boot partition for flashing is p3.
-        SOURCE_PART="${ROOT_DEVICE}p7"
+        SOURCE_PART="${ROOT_DEVICE}p11"
         TARGET_BOOT_PART="${ROOT_DEVICE}p3"
         ;;
     *)
-        echo "ERROR: Invalid or unsupported mender_boot_part value: ${MENDER_PART_NUMBER}. Expected 6 or 7." >&2
+        echo "ERROR: Invalid or unsupported mender_boot_part value: ${MENDER_PART_NUMBER}. Expected 10 or 11." >&2
         exit 1
         ;;
 esac
